auth_enabled: false

# Configuração do servidor HTTP
server:
  http_listen_port: 3100
  grpc_listen_port: 9096

  # Timeouts
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 120s

  # Logs do próprio Loki
  log_level: info

# Configuração do distributor (recebe logs)
distributor:
  ring:
    kvstore:
      store: inmemory

# Configuração do ingester (processa e armazena logs)
ingester:
  # Lifecycle
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

  # Chunk encoding
  # Aprendi que gzip oferece melhor compressão para logs JSON estruturados
  chunk_encoding: gzip

  # Chunk idle period (tempo antes de flush)
  chunk_idle_period: 5m

  # Chunk retain period
  chunk_retain_period: 30s

  # Max chunk age
  max_chunk_age: 1h

  # Tamanho máximo de chunk transferido
  chunk_target_size: 1536000  # ~1.5MB

  # Flush em shutdown
  flush_on_shutdown: true

# Configuração de schema (como logs são indexados)
schema_config:
  configs:
    # Schema v11 (recomendado)
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: nexus_index_
        period: 24h  # Índice novo a cada 24h

# Configuração de armazenamento
storage_config:
  boltdb_shipper:
    # Diretório de índices
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h

    # Diretório compartilhado de índices
    shared_store: filesystem

  filesystem:
    # Diretório de chunks (logs propriamente ditos)
    directory: /loki/chunks

# Configuração de limites
# Implementei limites generosos mas seguros para evitar OOM
limits_config:
  # Reject logs antigos (24h)
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 dias

  # Taxa de ingestão (por tenant/stream)
  ingestion_rate_mb: 10  # 10MB/s
  ingestion_burst_size_mb: 20  # 20MB burst

  # Limites de query
  max_query_length: 721h  # 30 dias
  max_query_parallelism: 32
  max_streams_per_user: 10000
  max_entries_limit_per_query: 10000

  # Limites de label
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30

  # Retention por stream (padrão: sem limite, controlado por compactor)
  # retention_period: 0

# Configuração de compactor (limpeza de dados antigos)
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

  # Período de retenção global
  # Decidi manter 30 dias de logs para debugging e análise
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Configuração de retenção por stream (opcional)
# Permite diferentes períodos de retenção por tipo de log
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h  # 30 dias

# Configuração de chunk cache (Redis no futuro)
# chunk_store_config:
#   chunk_cache_config:
#     redis:
#       endpoint: redis:6379
#       timeout: 100ms
#       expiration: 1h

# Configuração de query frontend (para queries paralelas)
query_range:
  # Divisão de queries longas em sub-queries
  split_queries_by_interval: 24h

  # Cache de resultados
  results_cache:
    cache:
      # Embedded cache (usar Redis/Memcached em produção)
      embedded_cache:
        enabled: true
        max_size_mb: 100
        ttl: 24h